import React, { useState } from 'react';
import img1 from "/car/1.png"
import img2 from "/car/2.png"
import img3 from "/car/4.png"
import img4 from "/car/3.png"
import CarCard from './CarCard';

export default function CarDetails() {
    const CarProviders = [
        {
            name: "Jacob Jones",
            location: "New York, USA",
            image: img1,
            price: "$500",
            rating: 5,
            availability: "Available",
            mileage: "15,000 km",
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            year: 2022,
        },
        {
            name: "Emily Smith",
            location: "Los Angeles, USA",
            image: img1,
            price: "$450",
            rating: 4.8,
            availability: "Available",
            mileage: "12,500 km",
            transmission: "Manual",
            fuelType: "Diesel",
            seats: 4,
            year: 2021,
        },
        {
            name: "Michael Johnson",
            location: "Chicago, USA",
            image: img2,
            price: "$600",
            rating: 4.9,
            availability: "Not Available",
            mileage: "18,200 km",
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            year: 2023,
        },
        {
            name: "Sophia Williams",
            location: "Houston, USA",
            image: img3,
            price: "$550",
            rating: 4.7,
            availability: "Available",
            mileage: "20,000 km",
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 7,
            year: 2022,
        },
        {
            name: "Daniel Brown",
            location: "Miami, USA",
            image: img4,
            price: "$480",
            rating: 4.6,
            availability: "Available",
            mileage: "10,000 km",
            transmission: "Manual",
            fuelType: "Electric",
            seats: 5,
            year: 2024,
        },
        {
            name: "Olivia Martinez",
            location: "Seattle, USA",
            image: img1,
            price: "$530",
            rating: 4.9,
            availability: "Available",
            mileage: "13,500 km",
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            year: 2022,
        },
        {
            name: "William Davis",
            location: "Boston, USA",
            image: img2,
            price: "$590",
            rating: 4.8,
            availability: "Not Available",
            mileage: "22,000 km",
            transmission: "Manual",
            fuelType: "Diesel",
            seats: 5,
            year: 2021,
        },
        {
            name: "Ava Wilson",
            location: "Denver, USA",
            image: img3,
            price: "$520",
            rating: 4.7,
            availability: "Available",
            mileage: "9,800 km",
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 4,
            year: 2023,
        },
        {
            name: "James Anderson",
            location: "Austin, USA",
            image: img4,
            price: "$610",
            rating: 5,
            availability: "Available",
            mileage: "7,500 km",
            transmission: "Automatic",
            fuelType: "Electric",
            seats: 5,
            year: 2024,
        },
        {
            name: "Isabella Thomas",
            location: "San Diego, USA",
            image: img1,
            price: "$495",
            rating: 4.6,
            availability: "Not Available",
            mileage: "18,800 km",
            transmission: "Manual",
            fuelType: "Petrol",
            seats: 5,
            year: 2022,
        },
        {
            name: "Benjamin Taylor",
            location: "Dallas, USA",
            image: img2,
            price: "$550",
            rating: 4.7,
            availability: "Available",
            mileage: "14,500 km",
            transmission: "Automatic",
            fuelType: "Diesel",
            seats: 7,
            year: 2023,
        },
        {
            name: "Mia Moore",
            location: "San Francisco, USA",
            image: img3,
            price: "$640",
            rating: 4.9,
            availability: "Available",
            mileage: "11,700 km",
            transmission: "Automatic",
            fuelType: "Electric",
            seats: 5,
            year: 2024,
        },
        {
            name: "Lucas Lee",
            location: "Orlando, USA",
            image: img1,
            price: "$475",
            rating: 4.5,
            availability: "Available",
            mileage: "21,000 km",
            transmission: "Manual",
            fuelType: "Petrol",
            seats: 5,
            year: 2021,
        },
        {
            name: "Amelia Harris",
            location: "Las Vegas, USA",
            image: img2,
            price: "$510",
            rating: 4.8,
            availability: "Available",
            mileage: "15,300 km",
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 4,
            year: 2023,
        },
        {
            name: "Henry Clark",
            location: "Phoenix, USA",
            image: img3,
            price: "$520",
            rating: 4.6,
            availability: "Available",
            mileage: "13,000 km",
            transmission: "Automatic",
            fuelType: "Diesel",
            seats: 7,
            year: 2022,
        },
        {
            name: "Evelyn Lewis",
            location: "Portland, USA",
            image: img4,
            price: "$600",
            rating: 4.9,
            availability: "Not Available",
            mileage: "16,400 km",
            transmission: "Automatic",
            fuelType: "Electric",
            seats: 5,
            year: 2024,
        },
        {
            name: "Alexander Walker",
            location: "Atlanta, USA",
            image: img1,
            price: "$490",
            rating: 4.7,
            availability: "Available",
            mileage: "12,900 km",
            transmission: "Manual",
            fuelType: "Petrol",
            seats: 5,
            year: 2022,
        },
        {
            name: "Charlotte Hall",
            location: "Columbus, USA",
            image: img2,
            price: "$560",
            rating: 4.8,
            availability: "Available",
            mileage: "8,500 km",
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            year: 2023,
        },
        {
            name: "Jack Allen",
            location: "Kansas City, USA",
            image: img3,
            price: "$530",
            rating: 4.7,
            availability: "Not Available",
            mileage: "22,300 km",
            transmission: "Automatic",
            fuelType: "Diesel",
            seats: 7,
            year: 2021,
        },
        {
            name: "Grace Young",
            location: "Minneapolis, USA",
            image: img4,
            price: "$580",
            rating: 4.9,
            availability: "Available",
            mileage: "19,600 km",
            transmission: "Manual",
            fuelType: "Electric",
            seats: 5,
            year: 2024,
        },
        {
            name: "Ethan King",
            location: "Detroit, USA",
            image: img1,
            price: "$495",
            rating: 4.6,
            availability: "Available",
            mileage: "17,800 km",
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            year: 2022,
        },
        {
            name: "Harper Scott",
            location: "Tampa, USA",
            image: img2,
            price: "$510",
            rating: 4.7,
            availability: "Available",
            mileage: "14,000 km",
            transmission: "Manual",
            fuelType: "Diesel",
            seats: 5,
            year: 2021,
        },
        {
            name: "Sebastian Adams",
            location: "Raleigh, USA",
            image: img3,
            price: "$545",
            rating: 4.8,
            availability: "Available",
            mileage: "11,500 km",
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            year: 2023,
        },
        {
            name: "Victoria Baker",
            location: "Nashville, USA",
            image: img4,
            price: "$620",
            rating: 5,
            availability: "Available",
            mileage: "9,200 km",
            transmission: "Automatic",
            fuelType: "Electric",
            seats: 5,
            year: 2024,
        },
        {
            name: "Matthew Perez",
            location: "Charlotte, USA",
            image: img1,
            price: "$485",
            rating: 4.5,
            availability: "Not Available",
            mileage: "23,000 km",
            transmission: "Manual",
            fuelType: "Petrol",
            seats: 5,
            year: 2021,
        },
        {
            name: "Ella Roberts",
            location: "Oklahoma City, USA",
            image: img3,
            price: "$575",
            rating: 4.8,
            availability: "Available",
            mileage: "13,800 km",
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            year: 2023,
        },
        {
            name: "David Turner",
            location: "Indianapolis, USA",
            image: img1,
            price: "$540",
            rating: 4.7,
            availability: "Available",
            mileage: "15,200 km",
            transmission: "Automatic",
            fuelType: "Diesel",
            seats: 7,
            year: 2022,
        },
        {
            name: "Scarlett Rivera",
            location: "Memphis, USA",
            image: img2,
            price: "$610",
            rating: 4.9,
            availability: "Available",
            mileage: "10,700 km",
            transmission: "Automatic",
            fuelType: "Electric",
            seats: 5,
            year: 2024,
        },
        {
            name: "Logan Campbell",
            location: "Louisville, USA",
            image: img3,
            price: "$500",
            rating: 4.6,
            availability: "Not Available",
            mileage: "20,500 km",
            transmission: "Manual",
            fuelType: "Petrol",
            seats: 5,
            year: 2021,
        },
        {
            name: "Zoe Mitchell",
            location: "Baltimore, USA",
            image: img4,
            price: "$595",
            rating: 4.8,
            availability: "Available",
            mileage: "12,600 km",
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            year: 2023,
        },
    ];




    return (
        <div className='py-16'>
            <div className="bg-white rounded-2xl shadow-lg w-full container mx-auto my-10 p-5">
                <div className="mb-5">
                    {/* Location Input */}
                    <div className="space-y-2">

                        <input
                            type="text"
                            placeholder="Find Location"
                            className="w-full p-3 border border-gray-200 rounded-lg"
                        />
                    </div>




                </div>
                {/* Search Button */}
                <div className="">
                    <button className="w-full bg-[#0064D2] text-white py-3 rounded-lg font-bold">
                        Search
                    </button>
                </div>
            </div>
            {/* Services Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 container mx-auto">
                {CarProviders.map((car, index) => (
                    <CarCard key={index} car={car} />
                ))}
            </div>
        </div>
    )
}